# Generated by Django 4.2.7 on 2023-11-29 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_employees_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='image',
            new_name='profile_pic',
        ),
    ]
